# Generated by Django 4.2.8 on 2025-10-25 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(choices=[('all', 'Tümü'), ('beans', 'Kahve Çekirdekleri'), ('ground', 'Öğütülmüş Kahve'), ('capsules', 'Kapsül Kahve'), ('equipment', 'Ekipmanlar'), ('accessories', 'Aksesuarlar')], max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('icon', models.CharField(help_text='Emoji veya karakter', max_length=10, verbose_name='İkon')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fiyat (₺)')),
                ('image', models.URLField(max_length=500, verbose_name='Ürün Görseli URL')),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='Menşe')),
                ('roast', models.CharField(blank=True, choices=[('Light', 'Açık Kavrum'), ('Medium', 'Orta Kavrum'), ('Medium-Dark', 'Orta-Koyu Kavrum'), ('Dark', 'Koyu Kavrum')], max_length=20, verbose_name='Kavurma Seviyesi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Puan')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Stokta')),
                ('featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TasteNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50, verbose_name='Tat Notu')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Tat Notu',
                'verbose_name_plural': 'Tat Notları',
                'ordering': ['order'],
            },
        ),
    ]
